---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.appName }}
        aadpodidbinding: {{ .Values.aadIdentityName }}
    spec:
      containers:
        - name: mi-adf-shir
          image: {{ .Values.image }}
          env:
            - name: AUTH_KEY
              value: "IR@491175e4-e4df-454d-b324-9ddb83ab7dcc@mi-ingestion-adf-test@ServiceEndpoint=mi-ingestion-adf-test.uksouth.datafactory.azure.net@U+g/uNOvvcspT2jwNNOBSeDXELHFTuZNsBbtaKmhrvs="
            - name: ENABLE_HA
              value: "{{ .Values.haEnabled }}"
            - name: NODE_NAME
              value: "{{ .Values.appName }}"
            - name: HA_PORT
              value: "{{ .Values.haPort }}"
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: "kubernetes.io/os"
          operator: "Equal"
          value: "windows"
          effect: "NoSchedule"