---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mi-adf-shir-deployment
  namespace: mi
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.job: glob:dev-*
spec:
  releaseName: mi-adf-shir
  chart:
    git: git@github.com:hmcts/shared-services-flux
    path: k8s/release/mi/mi-adf-shir
    ref: setup-sbox-shir-charts
  values:
    labels:
      app.kubernetes.io/instance: mi-adf-shir-deployment
      app.kubernetes.io/name: mi-adf-shir-deployment
    image: sdshmctspublic.azurecr.io/mi/adf-integration-runtime:dev-3ee27d5
    managedIdentityClientId: 9278a876-6f8a-489d-9053-01c996a7b6f6
    environment: "sbox"
    resourcegroup: "mi-sbox-rg"
    subscriptionId: "a8140a9e-f1b0-481f-a4de-09e2ee23f7ab"
    tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"